spring:
  application:
    name: auth-service


  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


jwt:
  secret: /f7+9Bc8p105yE9V0a5RDyGY++g0ZkFDPNxPpUMJ8tM=
  expiration: 3600000
  refresh-expiration: 604800000