spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:E:/commercehub/config-repo

server:
  port: 8888